version: "3.9"

services:
  postgres_auth:
    container_name: auth_db
    hostname: auth_db
    image: postgres:latest
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_DB: auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:4.0-management
    ports:
      - "15672:15672"
      - "5672:5672"

  auth:
    container_name: auth
    build: ./src/auth-service
    environment:
      - PORT=3001
      - POSTGRES_HOST=auth_db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=auth
      - RMQ_URL=amqp://rabbitmq:5672
      - RABBITMQ_AUTH_QUEUE=auth_queue
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq
      - postgres_auth
    links:
      - postgres_auth

  api:
    container_name: api
    build: ./src/api-gateway
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - RABBITMQ_AUTH_QUEUE=auth_queue
    depends_on:
      - rabbitmq
      - auth
